### ISSUE TITLE
Too slow initial load

### ISSUE THREAD

**Issue by danames** [BYU-Hydroinformatics/warehouse#1]
Just installed warehouse. First run took almost 30 seconds to load with no user feedback. Let's add some kind of feedback indicating that the warehouse index is being built.

**Comment by rfun** [comment]
This has been significantly improved. I have updated the way metadata is fetched from conda. The old way required downloading all the app package files (they are small, but still take time to fetch each one) and then extracting the metadata from them. However, from version 0.2.5 onwards, the metadata can be retrieved much easier by using the License field in conda search command as a place to put all the required metadata. This approach will work for any application that is submitted or re-submitted via a Warehouse version 0.2.5 or higher. 
The metadata building code is backwards compatible so it falls back to the old method in case the app hasn't been pushed with the new warehouse version. 
Also there is a loading indicator when the metadata library is being built so the user doesn't just sit there waiting without any feedback.
